export const NUMBER_ABBREVIATION = {
  DEFAULT: 1,
  M: 1_000_000,
  Bn: 1_000_000_000,
  Tr: 1_000_000_000_000,
  Qn: 1_000_000_000_000_000,
};

export const NUMBER_ABBREVIATION_RANGE = {
  DEFAULT: [0, NUMBER_ABBREVIATION.M],
  M: [NUMBER_ABBREVIATION.M, NUMBER_ABBREVIATION.Bn],
  Bn: [NUMBER_ABBREVIATION.Bn, NUMBER_ABBREVIATION.Tr],
  Tr: [NUMBER_ABBREVIATION.Tr, NUMBER_ABBREVIATION.Qn],
  Qn: [NUMBER_ABBREVIATION.Qn, Number.POSITIVE_INFINITY],
};

export const NUMBER_ABBREVIATION_DESCRIPTION = {
  DEFAULT: '',
  M: 'M',
  Bn: 'Bn',
  Tr: 'Tr',
  Qn: 'Qn',
};

export const CURRENCY_SYMBOL = {
  USD: '$',
  BTC: '₿',
};
