import {
  GOOGLE_WEB_CLIENT_ID as GOOGLE_WEB_CLIENT_ID_ENV,
  CMC_API_KEY as CMC_API_KEY_ENV,
  MESSARI_API_KEY as MESSARI_API_KEY_ENV,
  FIREBASE_API_KEY as FIREBASE_API_KEY_ENV,
  FIREBASE_AUTH_DOMAIN as FIREBASE_AUTH_DOMAIN_ENV,
  FIREBASE_PROJECT_ID as FIREBASE_PROJECT_ID_ENV,
  FIREBASE_STORAGE_BUCKET as FIREBASE_STORAGE_BUCKET_ENV,
  FIREBASE_MESSAGING_SENDER_ID as FIREBASE_MESSAGING_SENDER_ID_ENV,
  FIREBASE_APP_ID as FIREBASE_APP_ID_ENV,
  FIREBASE_MEASUREMENT_ID as FIREBASE_MEASUREMENT_ID_ENV,
} from '@env';

export const CMC_API_KEY = CMC_API_KEY_ENV;

export const MESSARI_API_KEY = MESSARI_API_KEY_ENV;

export const FIREBASE_API_KEY = FIREBASE_API_KEY_ENV;

export const FIREBASE_AUTH_DOMAIN = FIREBASE_AUTH_DOMAIN_ENV;

export const FIREBASE_PROJECT_ID = FIREBASE_PROJECT_ID_ENV;

export const FIREBASE_STORAGE_BUCKET = FIREBASE_STORAGE_BUCKET_ENV;

export const FIREBASE_MESSAGING_SENDER_ID = FIREBASE_MESSAGING_SENDER_ID_ENV;

export const FIREBASE_APP_ID = FIREBASE_APP_ID_ENV;

export const FIREBASE_MEASUREMENT_ID = FIREBASE_MEASUREMENT_ID_ENV;

export const GOOGLE_WEB_CLIENT_ID = GOOGLE_WEB_CLIENT_ID_ENV;
